version: '3'
services:
  webdav:
    image: bytemark/webdav
    ports:
      - "80:80"
      - "8085:443"
    environment:
      AUTH_TYPE: Digest
      USERNAME: alice
      PASSWORD: secret1234
    volumes:
      - ~/Downloads/keeweb-gh-pages/webdav:/var/lib/dav