#Make a job that build and push each image on docker.io
name: Docker build and push

on: [push]

jobs:
  docker:
    runs-on: self-hosted

    steps:
    -
      name: Checkout the code
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - 
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          gridexx/keeweb
    -
      name: Build and push the Dockerfile with tags
      uses: docker/build-push-action@v3
      with:
        file: ./Dockerfile
        push: true
        context: .
        tags: ${{ steps.meta.outputs.tags }}